apiVersion: v1
kind: Service
metadata:
  name: flask-bluegreen-active-svc
  namespace: flask-app-hml
spec:
  selector:
    app: flask-app-bluegreen
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: flask-bluegreen-preview-svc
  namespace: flask-app-hml
spec:
  selector:
    app: flask-app-bluegreen
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080