apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: flask-app-bluegreen-dp
  namespace: flask-app-hml
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app-bluegreen
  template:
    metadata:
      labels:
        app: flask-app-bluegreen
    spec:
      containers:
        - name: flask-app-bluegreen-container
          image: <ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/flask-app-bluegreen:v1
          ports:
            - containerPort: 8080
  strategy:
    type: BlueGreen
    blueGreen:
      activeService: flask-bluegreen-active-svc
      previewService: flask-bluegreen-preview-svc
      autoPromotionEnabled: false