---
- name: Get ArgoCD Credentials
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Extrair o hostname do LoadBalancer
      ansible.builtin.shell: |
        kubectl get svc argocd-server -n argocd -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'
      register: argocd_url
      args:
        executable: /bin/bash

    - name: Exibir senha inicial do ArgoCD
      ansible.builtin.shell: |
        kubectl get secret argocd-initial-admin-secret -n argocd -o jsonpath="{.data.password}" | base64 -d; echo
      register: argocd_admin_password
      args:
        executable: /bin/bash

    - name: Mostrar senha e URL no output
      ansible.builtin.debug:
        msg: 
          - "✅ ArgoCD instalado com sucesso!" 
          - "ARGOCD URL: {{ argocd_url.stdout }} "
          - "ARGOCD USERNAME: admin"
          - "ARGOCD PASSWORD: {{ argocd_admin_password.stdout }}"