---
- name: Instala o ArgoCD Rollouts no cluster Kubernetes
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Criar namespace argocd
      community.kubernetes.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: argo-rollouts

    - name: Instalar ArgoCD via manifest oficial
      ansible.builtin.shell: |
        kubectl apply -n argo-rollouts -f https://github.com/argoproj/argo-rollouts/releases/latest/download/install.yaml