---
- name: Instala o ArgoCD Rollouts no cluster Kubernetes
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Criar namespace argocd
      community.kubernetes.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: argo-rollouts

    - name: Instalar ArgoCD via manifest oficial
      ansible.builtin.shell: |
        kubectl apply -n argo-rollouts -f https://github.com/argoproj/argo-rollouts/releases/latest/download/install.yaml

    - name: Baixando CLI ArgoCD Rollouts CLI
      ansible.builtin.shell: |
        curl -sLO https://github.com/argoproj/argo-rollouts/releases/latest/download/kubectl-argo-rollouts-linux-amd64

    - name: Instalando & Configurando ArgoCD Rollouts CLI
      ansible.builtin.shell: |
        chmod +x kubectl-argo-rollouts-linux-amd64
        sudo mv kubectl-argo-rollouts-linux-amd64 /usr/local/bin/kubectl-argo-rollouts

