apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-dp
  namespace: flask
spec:
  selector:
    matchLabels:
      app: flask-app
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: app-sre-container
        image: jayakuza/app:v1
        imagePullPolicy: Always