apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-in
  namespace: flask
spec:
  rules:
  - host: ingress-jg.ddns.net
    http: 
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flask-svc
            port:
              number: 8080