apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: flask-app-canary-dp
  namespace: flask-app-hml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app-canary
  template:
    metadata:
      labels:
        app: flask-app-canary
    spec:
      containers:
        - name: flask-app-canary-container
          image: 590183702475.dkr.ecr.us-east-1.amazonaws.com/flask-app:v1 
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
  strategy:
    type: Canary
    canary:
      steps:
        - setWeight: 20
        - pause: { duration: 30s }
        - setWeight: 50
        - pause: { duration: 30s }
        - setWeight: 100
