apiVersion: v1
kind: Service
metadata:
  name: flask-app-canary-svc
  namespace: flask-app-hml
spec:
  selector:
    app: flask-app-canary
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 8080