apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: flask-app-dp
  namespace: flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-container
          image: 590183702475.dkr.ecr.us-east-1.amazonaws.com/flask-app:v1 
          # Image flask-app:v2 -> Porta 8181 = erro no healthcheck
          # Image flask-app:v3 -> Porta 8080 + Hello World - v3
          ports:
            - containerPort: 8080
          # Para fazer o rollout automatico é necessário readinessProbe.
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
  strategy:
    type: Canary
    canary:
      steps:
        # Config de Canary
        # Começa com 20%, após 30s vai para 50%, após 30s vai para 100%
        - setWeight: 20
        - pause: { duration: 30s }
        - setWeight: 50
        - pause: { duration: 30s }
        - setWeight: 100
