apiVersion: v1
kind: Secret
metadata:
  name: flask-app-bluegreen
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://git-codecommit.us-east-1.amazonaws.com/v1/repos/flask-app-bluegreen
  username: {git-username}
  password: {git-password}


---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app-bluegreen
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://git-codecommit.us-east-1.amazonaws.com/v1/repos/flask-app-bluegreen
    targetRevision: HEAD
    path: "."
  destination:
    server: https://kubernetes.default.svc
    namespace: flask-app-hml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

