name: argocd-rollouts-cicd
run-name: ArgoRollouts CICD
on:
  push:
    branches:
      - "main"
    paths:
      - "**.tf"
      - "**.yml"
      - "**.yaml"
jobs:
  install-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Terraform
        run: |
          wget -O - https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(grep -oP '(?<=UBUNTU_CODENAME=).*' /etc/os-release || lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update -y && sudo apt install terraform -y
      - name: Install Terraform Lint (tflint)
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
      - name: Install Terraform Sec Lint (tfsec)
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
      - name: Install Infracost
        run: |
          curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
  init-terraform:
    runs-on: ubuntu-latest
    needs: install-packages
    steps:
      - uses: actions/checkout@v4
      - name: Run Terraform Init
        run: cd ./Terraform && terraform init
  verify-terraform-lint:
    runs-on: ubuntu-latest
    needs: install-packages
    steps:
      - uses: actions/checkout@v4
      - name: Run tflint
        run: tflint --init && tflint
  verify-terraform-sec:
    runs-on: ubuntu-latest
    needs: install-packages    
    steps:
      - uses: actions/checkout@v4
      - name: Run tfsec
        run: tfsec .
  verify-ansible-lint:
    runs-on: ubuntu-latest
    needs: install-packages
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        with:
          setup_python: "true"
          working_directory: "../Ansible/playbooks"
