name: argocd-rollouts-cicd
run-name: ${{ github.actor }} Pipeline deploy
on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "*.txt"
      - ".md"
      - ".tf"
      - "init.py"
      - ".gitignore"
      - ".yaml"
jobs:
  argocd-rollouts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: INSTALL PACKAGES
        run: |
          echo "v1"
          # A pipeline vai fazer o Build do APP
          # Rodar o SNYK SCAN
          # VALIDAR SE A BRANCH FOR MAIN = ABRIR PR automatica da dev para main no repo de codigo
          # DOCKER PUSH para o ECR
          # 
